keboola/php-table-backend-utils

src/Table/SynapseTableReflection.php

Check only views that has SQL definition.

fixup SynapseTableReflection::getDependentViews

---

README.md
src/Database/DatabaseReflectionInterface.php
src/Database/SynapseDatabaseReflection.php
tests/Functional/Database/SynapseDatabaseReflectionTest.php

```
interface DatabaseReflectionInterface
{
public function getUsersNames(?string $like = null): array;
public function getRolesNames(?string $like = null): array;
}
```

Database reflection

---

composer.json
src/Table/SynapseTableReflection.php
tests/Functional/Table/SynapseTableReflectionTest.php

Fixes https://github.com/keboola/php-table-backend-utils/issues/11

Synapse: table size

---

composer.json

Zafixoval jsem verzi datatype na 4.7.* aby se dal vydat opravny fix verze v0.4

fixup 4.8.0

---

src/Table/SynapseTableReflection.php
tests/Functional/Table/SynapseTableReflectionTest.php

fix get object id if table or schema includes dot

---

src/Table/SynapseTableReflection.php
tests/Functional/Table/SynapseTableReflectionTest.php

JIRA: https://keboola.atlassian.net/browse/KBC-1253

KBC-1253 [Synapse] distribution and distribution key reflection

---

src/Auth/SynapseGrantQueryBuilder.php
src/Auth/SynapseUserReflection.php
src/Database/SynapseDatabaseReflection.php
src/Escaping/SynapseQuote.php
src/Schema/SynapseSchemaQueryBuilder.php
src/Schema/SynapseSchemaReflection.php
src/Table/SynapseTableQueryBuilder.php
src/Table/SynapseTableReflection.php
src/View/SynapseViewReflection.php
tests/Functional/Auth/SynapseGrantQueryBuilderTest.php
tests/Functional/Schema/SynapseSchemaQueryBuilderTest.php
tests/Functional/Schema/SynapseSchemaReflectionTest.php
tests/Functional/SynapseBaseCase.php
tests/Functional/Table/SynapseTableQueryBuilderTest.php
tests/Functional/Table/SynapseTableReflectionTest.php
tests/Unit/Escaping/SynapseQuoteTest.php
tests/Unit/Table/SynapseTableQueryBuilderTest.php

We are no longer using DBAL platform for escaping identifiers.

use new escaping everywhere

---

src/Table/SynapseTableQueryBuilder.php
src/Table/SynapseTableReflection.php
tests/Functional/Table/SynapseTableQueryBuilderTest.php

Chybyčka se vloudila, omylem sem zavřel předchozí PR https://github.com/keboola/php-table-backend-utils/pull/20
JIRA: https://keboola.atlassian.net/browse/KBC-1518

KBC-1518 part 2 Create table from definition object

---

src/Table/SynapseTableReflection.php

JIRA: https://keboola.atlassian.net/browse/KBC-1560

KBC-1560 use count_big not count

---

src/Escaping/RedshiftQuote.php
tests/Unit/Escaping/RedshiftQuoteTest.php

Fixes part of : https://keboola.atlassian.net/browse/KBC-1609
Identifier je obloz z https://github.com/keboola/php-db-import/blob/02c72c6379310c52ae4e008dd7cf10bcafb69b29/src/RedshiftBase.php#L637

Escaping\RedshiftQuote helper

---

src/Table/SynapseTableReflection.php
src/TableNotExistsReflectionException.php
tests/Functional/Table/Synapse/SynapseTableQueryBuilderTest.php

KBC-1665 fix workspace unload table error

---

phpstan-baseline.neon
phpstan.neon
src/Table/Synapse/Assert.php
src/Table/SynapseTableReflection.php
tests/Functional/Table/Synapse/SynapseTableReflectionTest.php
tests/Unit/Table/Synapse/AssertTest.php
tests/Unit/Table/Synapse/TableIndexDefinitionTest.php

JIRA: https://keboola.atlassian.net/browse/KBC-1819

KBC-1819 Synapse implement indexes reflection

---

src/Table/Exasol/ExasolTableQueryBuilder.php
tests/Unit/Table/Exasol/ExasolTableQueryBuilderTest.php

Check table name when creating table. Dot is not supported
Jira: https://keboola.atlassian.net/browse/KBC-1785
Conenction: https://github.com/keboola/connection/pull/3407

KBC-1785 validate table name

---

README.md
composer.json
src/Connection/Exasol/ExasolConnection.php
src/Connection/Exasol/ExasolDriver.php
src/Connection/Snowflake/Exception/CannotAccessObjectException.php
src/Connection/Snowflake/Exception/ConnectionException.php
src/Connection/Snowflake/Exception/DriverException.php
src/Connection/Snowflake/Exception/StringTooLongException.php
src/Connection/Snowflake/Exception/WarehouseTimeoutReached.php
src/Connection/Snowflake/Result.php
src/Connection/Snowflake/SnowflakeConnection.php
src/Connection/Snowflake/SnowflakeConnectionFactory.php
src/Connection/Snowflake/SnowflakeDSNGenerator.php
src/Connection/Snowflake/SnowflakeDriver.php
src/Connection/Snowflake/SnowflakeExceptionConverter.php
src/Connection/Snowflake/SnowflakePlatform.php
src/Connection/Snowflake/SnowflakeSchemaManager.php
src/Connection/Snowflake/SnowflakeStatement.php
src/Connection/Teradata/TeradataDriver.php
src/Connection/Teradata/TeradataSchemaManager.php
src/Escaping/Snowflake/SnowflakeQuote.php
tests/Functional/Connection/Snowflake/SnowflakeBaseCase.php
tests/Functional/Connection/Snowflake/TestConnectionTest.php
tests/Functional/Exasol/ExasolBaseCase.php
tests/Functional/Teradata/TeradataBaseCase.php
tests/Unit/Connection/Snowflake/SnowflakeDSNGeneratorTest.php
tests/Unit/Connection/Snowflake/SnowflakeExceptionConverterTest.php
tests/Unit/Escaping/SnowflakeQuoteTest.php

JIRA: https://keboola.atlassian.net/browse/KBC-2218 + https://keboola.atlassian.net/browse/KBC-2219 (Quote implementation was also needed for this)
- SNFLK dbal connection implementation 
-  Exception handling
-  Driver
-  Connection + Factory
- Update to DBAL 3.2 and fix version to ^3.2

KBC-2218 SNFLK Connection

---

src/Column/ColumnInterface.php
src/Column/Exasol/ExasolColumn.php
src/Column/Snowflake/SnowflakeColumn.php
src/Column/SynapseColumn.php
src/Column/Teradata/TeradataColumn.php
src/Table/Exasol/ExasolTableReflection.php
tests/Functional/Table/Exasol/ExasolTableReflectionTest.php
tests/Unit/Column/Exasol/ExasolColumnTest.php
tests/Unit/Column/Snowflake/SnowflakeColumnTest.php

trosku jsem se rozsoup'...
Implementace v Connection prijde az s TableReflection

KBC-2222 Add Snflk column class

---

src/Database/Snowflake/SnowflakeDatabaseReflection.php
tests/Functional/Database/Snowflake/SnowflakeDatabaseReflectionTest.php

JIRA: https://keboola.atlassian.net/browse/KBC-2219

KBC-2219 Snowflake database reflection

---

src/Escaping/Snowflake/SnowflakeQuote.php
src/Table/Exasol/ExasolTableQueryBuilder.php
src/Table/Snowflake/SnowflakeTableDefinition.php
src/Table/Snowflake/SnowflakeTableQueryBuilder.php
src/Table/Snowflake/SnowflakeTableReflection.php
src/Table/Teradata/TeradataTableQueryBuilder.php
tests/Functional/Connection/Snowflake/SnowflakeBaseCase.php
tests/Functional/Table/Snowflake/SnowflakeTableQueryBuilderTest.php
tests/Functional/Table/Snowflake/SnowflakeTableReflectionTest.php
tests/Unit/Table/Snowflake/SnowflakeTableQueryBuilderTest.php

Jira: https://keboola.atlassian.net/browse/KBC-2221
Full implementation of `TableDefinitionInterface`, `TableQueryBuilderInterface`, `TableReflectionInterface`

KBC-2221 snlkf table reflection

---

src/Table/Snowflake/SnowflakeTableReflection.php
src/View/Snowflake/SnowflakeViewReflection.php
tests/Functional/View/Exasol/ExasolViewReflectionTest.php
tests/Functional/View/Snowflake/SnowflakeViewReflectionTest.php

Jira: https://keboola.atlassian.net/browse/KBC-2223
implementation of ViewReflectionInterface in SNFLK backend

KBC-2223 snflk view reflection

---

src/Schema/Snowflake/SnowflakeSchemaQueryBuilder.php
src/Schema/Snowflake/SnowflakeSchemaReflection.php
tests/Functional/Schema/Snowflake/SnowflakeSchemaQueryBuilderTest.php
tests/Functional/Schema/Snowflake/SnowflakeSchemaReflectionTest.php

Jira: https://keboola.atlassian.net/browse/KBC-2220
SNFLK implementation of `SchemaReflectionInterface`

KBC-2220 Schema interface in snowflake

---

README.md

Ked  chcem nastavit pripojenie v PHPStorme tak bez toho ze zmazem port sa nepripojim

Add information about setup in PHPStorm

---

src/View/Teradata/TeradataViewReflection.php
tests/Functional/View/Teradata/TeradataViewReflectionTest.php

Jira: https://keboola.atlassian.net/browse/KBC-2386
je potreba pridat do `.env` novy env `TERADATA_DB_PREFIX`

Roman kbc 2386 teradata viewreflection

---

src/Connection/Exasol/ExasolConnectionFactory.php
src/Connection/Snowflake/SnowflakeConnectionFactory.php
src/Connection/Teradata/TeradataConnection.php

Díky tomu jdou nastavit middlewares pro doctrine, třeba logger apod,…

allow pass doctrine config to Connection on all backends

---

composer.json
src/Connection/ConnectionRetryWrapper.php
src/Connection/Teradata/TeradataDriver.php
src/Connection/Teradata/TeradataRetryPolicy.php
tests/Unit/Connection/Teradata/TeradataRetryPolicyTest.php

Add retry for Teradata use case when `Concurrent change conflict on database`

add ConnectionRetryWrapper and teradata implementation

---

src/Table/Teradata/TeradataTableQueryBuilder.php
tests/Functional/Table/Teradata/TeradataTableQueryBuilderTest.php
tests/Functional/Table/Teradata/TeradataTableReflectionTest.php
tests/Functional/Teradata/TeradataBaseCase.php

- implements `getCreateTableCommandFromDefinition`
- adds NoPI to create table sql

NoPI tables and sql from definition

---

tests/Functional/Teradata/Table/TeradataTableReflectionTest.php

jira https://keboola.atlassian.net/browse/KBC-2426
it looks weird but it passes for me now...

KBC-2426 Fix tests for dbStats

---

Dockerfile

Jira: https://keboola.atlassian.net/browse/KBC-2617

Use s3 to download exasol driver

---

src/Table/Snowflake/SnowflakeTableQueryBuilder.php

su debil a dal jsem tu pomlcku jen na prvni znak...

Fix underscore

---

src/Column/ColumnCollection.php
tests/Unit/Column/ColumnCollectionTest.php

we have introduced snowflake to IE lib and it doesn't have this restriction -> have to be removed or implemented extra for synapse

Remove check for number of columns

---

composer.json
src/Table/Snowflake/SnowflakeTableQueryBuilder.php
tests/Functional/Snowflake/Table/SnowflakeTableQueryBuilderTest.php
tests/Unit/Column/Snowflake/SnowflakeColumnTest.php
tests/Unit/Table/Snowflake/SnowflakeTableQueryBuilderTest.php

JIRA: https://keboola.atlassian.net/browse/KBC-2791 https://keboola.atlassian.net/browse/KBC-2893
DependsOn: https://github.com/keboola/php-datatypes/pull/62
- remove constraint on pks on SNFLK
- update of php-datatypes SNFLK default values

KBC-2893, KBC-2791

---

src/Table/Synapse/Assert.php
src/Table/SynapseTableReflection.php
tests/Functional/Synapse/Table/SynapseTableReflectionTest.php
tests/Unit/Table/Synapse/AssertTest.php

- fix wrong synapse clustered index definition

Synapse support multiple column clustered index

---

src/Table/Exasol/ExasolTableReflection.php
src/Table/Snowflake/SnowflakeTableReflection.php
src/Table/SynapseTableReflection.php
src/Table/TableReflectionInterface.php
src/Table/Teradata/TeradataTableReflection.php
tests/Functional/Exasol/Table/ExasolTableReflectionTest.php
tests/Functional/Snowflake/Table/SnowflakeTableReflectionTest.php
tests/Functional/Synapse/Table/SynapseTableReflectionTest.php
tests/Functional/Teradata/Table/TeradataTableReflectionTest.php

Jira: KBC-2924
add method to check if the table exists without extra overhead

KBC-2924 check if table exists

---

phpstan-baseline.neon
src/Column/Bigquery/BigqueryColumn.php
src/Connection/Synapse/SynapseDriver.php
tests/Functional/Synapse/Auth/BaseAuthTestCase.php
tests/Functional/Synapse/Connection/WlmContextTest.php
tests/Functional/Synapse/SynapseBaseCase.php

JIRA: KBC-3027
new `SynapseDriver` which is copy of Doctrine\DBAL\Driver\PDO\SQLSrv\Driver with support for setting wlm_context for each connection

KBC-3027 Add SynapseDriver with wlm context set option in driver options

---

src/Column/Bigquery/BigqueryColumn.php
src/Schema/Bigquery/BigquerySchemaReflection.php
src/Table/Bigquery/BigqueryTableDefinition.php
src/Table/Bigquery/BigqueryTableQueryBuilder.php
src/Table/Bigquery/BigqueryTableReflection.php
tests/Functional/Bigquery/BigqueryBaseCase.php
tests/Functional/Bigquery/Schema/BigquerySchemaReflectionTest.php
tests/Functional/Bigquery/Table/BigqueryTableQueryBuilderTest.php
tests/Functional/Bigquery/Table/BigqueryTableReflectionTest.php

Implementacia pomocnych metod pre import z csv pre I/E lib. 
V readme je navod ako si setupnut bq backend

Roman import file

---

src/Schema/Bigquery/BigquerySchemaReflection.php
src/Table/Bigquery/BigqueryTableReflection.php
tests/Functional/Bigquery/Schema/BigquerySchemaReflectionTest.php
tests/Functional/Bigquery/Table/BigqueryTableQueryBuilderTest.php
tests/Functional/Bigquery/Table/BigqueryTableReflectionTest.php

Pridal som vsade hlavne kontrolu na to ci existuje dataset alebo tabulka ono to teraz casto vratilo len prazdny vysledok

Big 51 roman import from ws

---

src/Table/Snowflake/SnowflakeTableReflection.php
src/TableNotExistsReflectionException.php
tests/Functional/Snowflake/Table/SnowflakeTableQueryBuilderTest.php
tests/Functional/Snowflake/Table/SnowflakeTableReflectionTest.php

KBC-3043 SnowflakeTableReflection now works with views

---

src/Connection/Teradata/TeradataPlatform.php

Jira: TER-18
~driver-common: https://github.com/keboola/php-storage-driver-common/pull/16~
driver-teradata: https://github.com/keboola/php-storage-driver-teradata/pull/44

TER-18 Table preview filters

---

src/Table/Teradata/TeradataTableQueryBuilder.php
tests/Functional/Teradata/Table/TeradataTableQueryBuilderTest.php

Jira: TER-58
Just QB to generate sql for add/drop col
Table utils: https://github.com/keboola/php-table-backend-utils/pull/88
Common: https://github.com/keboola/php-storage-driver-common/pull/21
TD Driver: https://github.com/keboola/php-storage-driver-teradata/pull/49
BQ Driver: https://github.com/keboola/php-storage-driver-bigquery/pull/27 
Connection: https://github.com/keboola/connection/pull/4120
SAPI: https://github.com/keboola/storage-api-php-client/pull/960

TER-58 Add/drop column

---

src/Table/Bigquery/BigqueryTableQueryBuilder.php
tests/Functional/Bigquery/Table/BigqueryTableQueryBuilderTest.php

Add support add/remove column

---

src/Table/Teradata/TeradataTableQueryBuilder.php
tests/Functional/Teradata/Table/TeradataTableQueryBuilderTest.php
tests/Unit/Table/Teradata/TeradataTableQueryBuilderTest.php

TER-59
query builder methods to add/drop pk
table utils: https://github.com/keboola/php-table-backend-utils/pull/91
TD driver : https://github.com/keboola/php-storage-driver-teradata/pull/51

TER-59 named constraint when creating table with PK
